name: template_flutter
description: Project Description

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  file_picker: ^5.2.5
  firebase_core: ^2.5.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0
  fluttertoast: ^8.1.2
  http: ^0.13.5
  intl: ^0.18.0
  package_info_plus: ^3.0.2
  path_provider: ^2.0.12
  provider: ^6.0.5
  share_plus: ^6.3.0
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.9
  firebase_messaging: ^14.2.2
  flutter_local_notifications: ^13.0.0
  connectivity_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_native_splash:
  image: assets/images/logo.png
  color: "#FFFFFF"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/logo.png
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  replace: true
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: assets/images/logo.png
    icon_size: 48
  macos:
    generate: true
    remove_alpha_ios: true
    image_path: assets/images/logo.png
  web:
    generate: true
    image_path: assets/images/logo.png
    icon_size: 48

flutter:
  uses-material-design: true
